### PR TITLE
Updates of ingest (for Django 1.11.7)

### PR DESCRIPTION
**Pull request by korvinos**
I updated ingest command for work with django 1.11.7 + now we check existence of file in db before ingesting + breath refactoring

### CODE REVIEW

**Comment by mortenwh** [comment]
The changes look good but needs to be tested. You may already have run the existing test locally but I would prefer the following (as we are now becoming more users of this package):

1. Integrate with Travis CI and Coveralls (see Nansat repos)
2. Create unit tests specific to each change
3. Merge sar-doppler into django-geo-spaas-sar-doppler

Point 2 is the most important. Point 1 is not strictly necessary for this specific pull request but would be very beneficial for future changes. Point 3 could just be added as a new issue....

**Comment by korvinos** [comment]
@mortenwh sar-doppler is private now, are we going to also make the sar-doppler-geospaas private?
Anyway, I will try to do all these things with CI and tests.

**Comment by mortenwh** [comment]
Great :) And yes, django-geo-spaas-sar-doppler should also be private before we merge the two...

**Comment by mortenwh** [comment]
I have now made this repos private...

**Comment by korvinos** [comment]
We won't be able to work with forks since you made it private

**Comment by mortenwh** [comment]
Ok - it is now public again :)

**Comment by mortenwh** [comment]
I added the bullet points above as issues and will merge.

**Pull request merged**
